/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // main: [{type: 'autogenerated', dirName: '.'}],

  main: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started/installation',
        'getting-started/ssl',
        'getting-started/limitations',
        'getting-started/upgrade-and-downgrade',
        'getting-started/permissions',
        'getting-started/gotchas',
      ],
    },
    {
      type: 'category',
      label: 'CI configuration',
      items: [
        'ci-configuration/basics',
        'ci-configuration/conditional-jobs',
        'ci-configuration/environment',
        'ci-configuration/secrets',
        'ci-configuration/private-docker-registry',
        'ci-configuration/before-after-scripts',
      ],
    },
    {
      type: 'category',
      label: 'Environment reference',
      items: [
        'environment-reference/server',
        'environment-reference/runner',
        'environment-reference/ui',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/building-docker-images-inside-jobs',
      ],
    },
  ],
};

module.exports = sidebars;
